# Generated by Django 3.1.2 on 2020-10-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Surname', models.CharField(max_length=20)),
                ('Other_names', models.CharField(max_length=20)),
                ('Username', models.CharField(max_length=10)),
                ('phone_number', models.PositiveIntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=15)),
                ('Confirm_password', models.CharField(max_length=15)),
            ],
        ),
    ]
