# Generated by Django 3.1.2 on 2020-10-28 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='Confirm_password',
        ),
    ]
