# Generated by Django 3.1.2 on 2020-10-26 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='phone_num',
            new_name='phone_number',
        ),
    ]
