# Generated by Django 3.1.2 on 2020-10-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quick_link', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('parent_guardian_contact_name', models.CharField(max_length=50)),
                ('parent_guardian_contact_no', models.PositiveIntegerField()),
                ('applicant_contact_no', models.PositiveIntegerField()),
                ('contact_address', models.CharField(max_length=50)),
                ('state_of_origin', models.CharField(max_length=50)),
                ('lga', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('ma', 'Male'), ('fe', 'Female'), ('ni', 'No Idea')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateTimeField()),
                ('name_of_institution', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=20)),
                ('level', models.CharField(choices=[('ese', '100L'), ('ref', '200L'), ('nidf', '300L'), ('ref', '200L'), ('nidf', '300L'), ('rek', '400L'), ('nsif', '500L')], max_length=20)),
                ('reason_for_application', models.CharField(choices=[('ed', 'Educational use'), ('pu', 'Professional use'), ('pu', 'personal use')], max_length=20)),
                ('semester', models.CharField(choices=[('f', 'first'), ('s', 'second')], max_length=20)),
                ('date_of_admission', models.DateTimeField()),
                ('microsoft', models.CharField(choices=[('w', 'ms-word'), ('e', 'ms-excel'), ('p', 'ms-powerpoint'), ('ps', 'more')], max_length=10)),
                ('mmore', models.CharField(max_length=30)),
                ('graphic', models.CharField(choices=[('c', 'corel draw'), ('p', 'photoshop'), ('cd', 'graphic design'), ('pxs', 'more')], max_length=10)),
                ('gmore', models.CharField(max_length=30)),
                ('programming', models.CharField(choices=[('b', 'basic'), ('v', 'visual-studio'), ('p', 'python'), ('pss', 'more')], max_length=10)),
                ('pmore', models.CharField(max_length=30)),
                ('duration', models.CharField(choices=[('a', '1 month intensive training'), ('b', '2 months graphic design training'), ('c', '1.5 months of basic programming'), ('d', '2 months app development'), ('e', '4 months professional graphics design'), ('f', '2.5 months of ms office training'), ('g', '2 months visual studio basics'), ('h', '4 months AI training'), ('i', '3 months genetic programming'), ('j', '3 months web development/hosting'), ('k', 'machine learning (3 months)'), ('l', '6 months advance AI training'), ('m', '2 months python basic')], max_length=10)),
                ('more', models.CharField(max_length=400)),
                ('Knowledge', models.CharField(choices=[('n', 'no'), ('y', 'yes, specify')], max_length=10)),
                ('specify', models.CharField(max_length=30)),
                ('experience_months', models.CharField(choices=[('ee', '1 month'), ('re', '2-3 months'), ('nif', '1-2 weeks')], max_length=20)),
                ('where_trained', models.CharField(max_length=30)),
                ('year_trained', models.IntegerField()),
                ('admission_date', models.DateTimeField()),
                ('course', models.CharField(max_length=30)),
                ('group_no', models.IntegerField()),
                ('paid_fees', models.IntegerField()),
                ('completion_date', models.DateTimeField()),
                ('date_of_commencement', models.IntegerField()),
                ('classes_days', models.CharField(max_length=50)),
                ('classes_hours', models.CharField(max_length=20)),
            ],
        ),
    ]
