# Generated by Django 3.1.2 on 2020-10-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quick_link', '0002_enrol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrol',
            name='admission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enrol',
            name='classes_days',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enrol',
            name='classes_hours',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='enrol',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enrol',
            name='course',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='enrol',
            name='date_of_commencement',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enrol',
            name='experience_months',
            field=models.CharField(blank=True, choices=[('ee', '1 month'), ('re', '2-3 months'), ('nif', '1-2 weeks')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='enrol',
            name='gmore',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='enrol',
            name='group_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enrol',
            name='mmore',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='enrol',
            name='more',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='enrol',
            name='paid_fees',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enrol',
            name='pmore',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='enrol',
            name='specify',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='enrol',
            name='where_trained',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='enrol',
            name='year_trained',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
