# Generated by Django 3.1.2 on 2020-10-27 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quick_link', '0004_remove_enrol_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrol',
            name='Knowledge',
        ),
        migrations.RemoveField(
            model_name='enrol',
            name='admission_date',
        ),
        migrations.RemoveField(
            model_name='enrol',
            name='applicant_contact_no',
        ),
        migrations.RemoveField(
            model_name='enrol',
            name='classes_days',
        ),
        migrations.RemoveField(
            model_name='enrol',
            name='classes_hours',
        ),
        migrations.RemoveField(
            model_name='enrol',
            name='completion_date',
        ),
        migrations.RemoveField(
            model_name='enrol',
            name='contact_address',
        ),
        migrations.RemoveField(
            model_name='enrol',
            name='course',
        ),
        migrations.RemoveField(
            model_name='enrol',
            name='date_of_admission',
        ),
        migrations.RemoveField(
            model_name='enrol',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='enrol',
            name='date_of_commencement',
        ),
        migrations.RemoveField(
            model_name='enrol',
            name='department',
        ),
        migrations.RemoveField(
            model_name='enrol',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='enrol',
            name='email',
        ),
        migrations.RemoveField(
            model_name='enrol',
            name='experience_months',
        ),
        migrations.RemoveField(
            model_name='enrol',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='enrol',
            name='gmore',
        ),
        migrations.RemoveField(
            model_name='enrol',
            name='graphic',
        ),
        migrations.RemoveField(
            model_name='enrol',
            name='group_no',
        ),
        migrations.RemoveField(
            model_name='enrol',
            name='level',
        ),
        migrations.RemoveField(
            model_name='enrol',
            name='lga',
        ),
        migrations.RemoveField(
            model_name='enrol',
            name='microsoft',
        ),
        migrations.RemoveField(
            model_name='enrol',
            name='mmore',
        ),
        migrations.RemoveField(
            model_name='enrol',
            name='more',
        ),
        migrations.RemoveField(
            model_name='enrol',
            name='name_of_institution',
        ),
        migrations.RemoveField(
            model_name='enrol',
            name='paid_fees',
        ),
        migrations.RemoveField(
            model_name='enrol',
            name='parent_guardian_contact_name',
        ),
        migrations.RemoveField(
            model_name='enrol',
            name='parent_guardian_contact_no',
        ),
        migrations.RemoveField(
            model_name='enrol',
            name='pmore',
        ),
        migrations.RemoveField(
            model_name='enrol',
            name='programming',
        ),
        migrations.RemoveField(
            model_name='enrol',
            name='reason_for_application',
        ),
        migrations.RemoveField(
            model_name='enrol',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='enrol',
            name='specify',
        ),
        migrations.RemoveField(
            model_name='enrol',
            name='state_of_origin',
        ),
        migrations.RemoveField(
            model_name='enrol',
            name='where_trained',
        ),
        migrations.RemoveField(
            model_name='enrol',
            name='year_trained',
        ),
        migrations.CreateModel(
            name='Enroldetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('parent_guardian_contact_name', models.CharField(max_length=50)),
                ('parent_guardian_contact_no', models.PositiveIntegerField()),
                ('applicant_contact_no', models.PositiveIntegerField()),
                ('contact_address', models.CharField(max_length=50)),
                ('state_of_origin', models.CharField(max_length=50)),
                ('lga', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('ma', 'Male'), ('fe', 'Female'), ('ni', 'No Idea')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateTimeField()),
                ('name_of_institution', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=20)),
                ('level', models.CharField(choices=[('ese', '100L'), ('ref', '200L'), ('nidf', '300L'), ('ref', '200L'), ('nidf', '300L'), ('rek', '400L'), ('nsif', '500L')], max_length=20)),
                ('reason_for_application', models.CharField(choices=[('ed', 'Educational use'), ('pu', 'Professional use'), ('pu', 'personal use')], max_length=20)),
                ('semester', models.CharField(choices=[('f', 'first'), ('s', 'second')], max_length=20)),
                ('date_of_admission', models.DateTimeField()),
                ('microsoft', models.CharField(choices=[('w', 'ms-word'), ('e', 'ms-excel'), ('p', 'ms-powerpoint'), ('ps', 'more')], max_length=10)),
                ('mmore', models.CharField(blank=True, max_length=30, null=True)),
                ('graphic', models.CharField(choices=[('c', 'corel draw'), ('p', 'photoshop'), ('cd', 'graphic design'), ('pxs', 'more')], max_length=10)),
                ('gmore', models.CharField(blank=True, max_length=30, null=True)),
                ('programming', models.CharField(choices=[('b', 'basic'), ('v', 'visual-studio'), ('p', 'python'), ('pss', 'more')], max_length=10)),
                ('pmore', models.CharField(blank=True, max_length=30, null=True)),
                ('duration', models.CharField(choices=[('a', '1 month intensive training'), ('b', '2 months graphic design training'), ('c', '1.5 months of basic programming'), ('d', '2 months app development'), ('e', '4 months professional graphics design'), ('f', '2.5 months of ms office training'), ('g', '2 months visual studio basics'), ('h', '4 months AI training'), ('i', '3 months genetic programming'), ('j', '3 months web development/hosting'), ('k', 'machine learning (3 months)'), ('l', '6 months advance AI training'), ('m', '2 months python basic')], max_length=10)),
                ('more', models.CharField(blank=True, max_length=400, null=True)),
                ('Knowledge', models.CharField(choices=[('n', 'no'), ('y', 'yes, specify')], max_length=10)),
                ('specify', models.CharField(blank=True, max_length=30, null=True)),
                ('experience_months', models.CharField(blank=True, choices=[('ee', '1 month'), ('re', '2-3 months'), ('nif', '1-2 weeks')], max_length=20, null=True)),
                ('where_trained', models.CharField(blank=True, max_length=30, null=True)),
                ('year_trained', models.IntegerField(blank=True, null=True)),
                ('admission_date', models.DateTimeField(blank=True, null=True)),
                ('course', models.CharField(blank=True, max_length=30, null=True)),
                ('group_no', models.IntegerField(blank=True, null=True)),
                ('paid_fees', models.IntegerField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('date_of_commencement', models.IntegerField(blank=True, null=True)),
                ('classes_days', models.CharField(blank=True, max_length=50, null=True)),
                ('classes_hours', models.CharField(blank=True, max_length=20, null=True)),
                ('enrol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quick_link.enrol')),
            ],
        ),
    ]
